import type { NextPage } from 'next';
import Head from 'next/head';

import Header from '../components/header';
import ConvertVideo from './convert-video';
import AboutSite from '../components/about-site';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Tool Box Virtual</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <ConvertVideo />
        <AboutSite />
      </main>

      <footer>

      </footer>
    </div>
  )
}

export default Home
